# Generated by Django 4.1.3 on 2022-11-06 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0003_record_remove_habit_title_habit_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='completed_amount',
        ),
        migrations.AddField(
            model_name='record',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='notes',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='record',
            name='habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='habit.habit'),
        ),
        migrations.AddConstraint(
            model_name='habit',
            constraint=models.UniqueConstraint(fields=('measurement', 'user', 'unit_of_measure'), name='habit_measurement'),
        ),
        migrations.AddConstraint(
            model_name='record',
            constraint=models.UniqueConstraint(fields=('habit', 'user', 'amount'), name='record_amount'),
        ),
    ]
