# Generated by Django 4.1.3 on 2022-11-07 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0004_remove_record_completed_amount_record_amount_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='habit',
            name='habit_measurement',
        ),
    ]
