# Generated by Django 4.1.3 on 2022-11-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0005_remove_habit_habit_measurement'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='record',
            name='record_amount',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='habit',
            new_name='habit_record',
        ),
        migrations.RemoveField(
            model_name='record',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='record',
            name='user',
        ),
        migrations.AddField(
            model_name='record',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='record',
            constraint=models.UniqueConstraint(fields=('habit_record', 'date', 'amount'), name='record_amount'),
        ),
    ]
