# Generated by Django 4.1.3 on 2022-11-07 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0006_remove_record_record_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='description',
        ),
    ]
